name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: echo 
      run: pwd
    - name: install
      run: ./${GITHUB_WORKSPACE}/install.sh
    - name: compile
      run: ./${GITHUB_WORKSPACE}/compile.sh

