name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: echo 
      run: pwd && ls
    - name: install
      run: chmod +x install.sh && ./install.sh
    - name: compile
      run: chmod +x compile.sh && ./compile.sh

